### ISSUE TITLE
Create net devices and channel for inter satellite communications

### ISSUE THREAD

**Issue by migrax** [ICARUS-ICN/icarus-ndnsim#8]
We can base this in a point to point communication model. No need for any link layer addresses.

This channel should take into account that communications between a pair of satellites are only possible if their line of sight never goes below 80km.

**Comment by pablosanuy** [comment]
Is it actually necessary to create a new NetDevice for the satellite, or can we just use the Sat2GroundNetDevice, creating different methods for attachment?
